---
- name: Task control - loop and when
  hosts: servers

  tasks:
    - name: Remove httpd
      package:
        name: httpd
        state: removed
      when: >
        ( ansible_distribution == "RedHat" and 
          ansible_memfree_mb < 512 )
        or
        ( ansible_distribution == "CentOS" and
          ansible_memfree_mb < 1024 )

    - name: show register on random module
      user:
        name: clarence
      register: output
    
    - name: show register result
      debug:
        var: output