---
- name: Handlers
  hosts: servers

  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: latest
        
    - name: Copy index.html
      copy:
        src: /tmp/index.html
        dest: /var/www/html/index.html
      notify:
        - restart_web

    - name: Copy nothing intended to fail
      copy:
        src: /tmp/nothing
        dest: /var/www/html/nothing
        
  handlers:
    - name: restart_web
      service:
        name: httpd
        state: restarted 